# Generated by Django 5.0.6 on 2024-06-11 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestados', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigoLibro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anioPublicacion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Logins',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('TipoUsuario', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='StockLibro',
            fields=[
                ('codigoLibro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prestamo.libro')),
                ('cantidadDisponible', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stock de Libro',
                'verbose_name_plural': 'Stocks de Libros',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPrestamo', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('fechaDevolucion', models.DateField(blank=True, null=True)),
                ('codigoLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.libro')),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.estado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
        migrations.CreateModel(
            name='Renovacion',
            fields=[
                ('idRenovacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRenovacion', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.estado')),
                ('idPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo')),
            ],
            options={
                'verbose_name': 'Renovación',
                'verbose_name_plural': 'Renovaciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('RUT', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.estado')),
                ('idTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.tipousuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='RUTUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.usuario'),
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('idDeuda', models.AutoField(primary_key=True, serialize=False)),
                ('diasRetraso', models.IntegerField()),
                ('montoDeuda', models.IntegerField()),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.estado')),
                ('idPrestamoLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo')),
                ('RUTUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.usuario')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
            },
        ),
    ]
