# Generated by Django 5.0.6 on 2024-06-11 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('idestados', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('codigoLibro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anioPublicacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuarios',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('TipoUsuario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockLibros',
            fields=[
                ('codigoLibro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prestamo.libros')),
                ('cantidadDisponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPrestamo', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('fechaDevolucion', models.DateField(blank=True, null=True)),
                ('codigoLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.libros')),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Renovaciones',
            fields=[
                ('idRenovacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRenovacion', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.estados')),
                ('idPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('RUT', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('Contacto', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.estados')),
                ('idTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.tipousuarios')),
            ],
        ),
        migrations.AddField(
            model_name='prestamos',
            name='RUTUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.usuarios'),
        ),
        migrations.CreateModel(
            name='Deudas',
            fields=[
                ('idDeuda', models.AutoField(primary_key=True, serialize=False)),
                ('diasRetraso', models.IntegerField()),
                ('montoDeuda', models.IntegerField()),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.estados')),
                ('idPrestamoLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamos')),
                ('RUTUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.usuarios')),
            ],
        ),
    ]
