# Generated by Django 5.0.2 on 2024-07-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Renovacion',
            new_name='Renovacione',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='idestados',
            new_name='idestado',
        ),
    ]
