# Generated by Django 5.0.6 on 2024-07-22 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0003_alter_prestamo_fechaprestamo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Renovacione',
            new_name='Renovacion',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='renovaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocklibro',
            name='cantidadTotal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stocklibro',
            name='cantidadDisponible',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('idMulta', models.AutoField(primary_key=True, serialize=False)),
                ('diasRetraso', models.IntegerField()),
                ('montoMulta', models.IntegerField()),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
            },
        ),
    ]
